# put common definitions in here
CC=g++
LIBRARY_PATH=/p/hpc/smartenergy/md/libraries
CFLAGS=-c -Wall -I.  -std=c++0x -pedantic -fPIC -O3
LDFLAGS = 
AR      = ar
ARFLAGS =
RANLIB  = ranlib
RM      = rm
ECHO    = echo

SHELL   = /bin/sh

.SILENT :
